### ISSUE TITLE
Milestone 4 to-do list

### ISSUE THREAD

**Issue by Kingslin0810** [UBC-MDS/DSCI_522_Group19_Wine_Quality_Score_Predictor#87]
- [x] Create a dependency diagram of the Makefile using `makefile2graph` and include it in the `README.md` file.
- [x] Add a new comment in the issue where we received the feedback from other students. 
* * https://github.com/UBC-MDS/data-analysis-review-2021/issues/4

To-do list:
- [x] Include instructions in the project `README`
** missing dockerfile instruction
- [x]  Wrap up the project in Docker container 
- [x]  Write a Docker file
- [x]  Use Docker Hub Automated Build to build your Docker image from your Dockerfile
- [x]  final report needs to use SVR (label in the tables) as opposed to SVC
